- apps/player/src/directives/index.js
- apps/player/src/directives/resize.js
- apps/player/src/tabs/Tabs.vue
- apps/player/src/tabs/components/TabHeaderItem.vue
- package-lock.json
- packages/components/src/components/tab/Header.vue
- renames HeaderItem to TabHeaderItem in the player app
- removes unused code from the Tab.Header in packages/components
- readds resize directive from old codebase
- removes redundant class name from the main div in the Tabs Component of the Player app
> feat(tabs): hides item labels if width is not sufficient to show all

- apps/player/src/store/reducers.js
- base.jest.config.js
- packages/build/dev-server.js
- packages/player/sagas/package-lock.json
- packages/player/sagas/package.json
- packages/player/state/last-action/index.js
- packages/player/state/last-action/reducer.js
- packages/player/state/last-action/reducer.test.js
- packages/player/state/last-action/selectors.js
> feat(player): add last action reducer

- apps/web-player/src/embed.js
- apps/web-player/src/lib/active-tab.js
> feat(web-player): add initial tab support

- apps/preview/docker-compose.yml
- apps/web-player/.build/webpack.config.dev.js
- apps/web-player/cypress/integration/url-parameters.spec.js
- apps/web-player/example/example.json
- apps/web-player/src/lib/url-params.js
> chore(web-player): fix chapter timestamp

- apps/player/package.json
- apps/player/src/Wrapper.vue
- apps/web-player/.build/webpack.config.cdn.js
- apps/web-player/.build/webpack.config.dev.js
- apps/web-player/.build/webpack.config.prod.js
- apps/web-player/example/example.html
- apps/web-player/example/example.json
> fix(web-player): fix share embed path

- apps/player/example/example.json
- packages/utils/url.js
fixes: #94
related: https://github.com/podlove/metalove/issues/8
> fix(player): harden url parser

- apps/player/src/store/index.js
- packages/player/sagas/helper.js
- packages/player/sagas/media-session.js
- packages/player/sagas/media-session.test.js
> feat(player): add media session api hooks

- apps/web-player/example/config.json
- packages/clients/src/apple-podcasts/index.js
- packages/clients/src/google-podcasts/index.js
- packages/clients/src/itunes/index.js
> chore(clients): update client list

- apps/player/cypress/integration/tab-share.spec.js
- apps/player/lang/de.json
- apps/player/lang/en.json
- package-lock.json
- packages/components/package.json
- packages/components/src/components/progress-bar/ProgressBar.vue
> chore(lang): update current playtime wording

- apps/player/src/components/subscribe-button/SubscribeButton.vue
- apps/web-player/example/example.html
- apps/web-player/src/templates/variant-l.html
- apps/web-player/src/templates/variant-m.html
- packages/components/src/components/timer/Timer.vue
> chore(web-player): fix layouts

- apps/player/cypress/integration/tab-playlist.spec.js
- apps/player/src/components/tab-playlist/components/Entry.vue
- packages/components/src/components/icons/__snapshots__/icon.test.js.snap
- packages/components/src/components/icons/states/MenuEmpty.vue
- packages/components/src/components/icons/types.js
> chore(player): remove numbers from playlist

- apps/player/package-lock.json
- apps/player/src/components/tab-chapters/components/Entry.vue
- package-lock.json
> fix(player): center chapter index

- apps/player/cypress/integration/tab-transcripts.spec.js
- apps/player/src/components/tab-transcripts/components/Render.vue
- apps/player/src/components/tab-transcripts/components/Search.vue
- apps/player/src/store/selectors/transcripts.js
- packages/player/sagas/transcripts.js
- packages/player/sagas/transcripts.test.js
- packages/player/state/transcripts/reducer.js
- packages/player/state/transcripts/reducer.test.js
- packages/player/state/transcripts/selectors.js
> fix(player): fix transcripts search navigation

- apps/player/src/components/tab-transcripts/components/Entry.vue
> chore(transcripts): add speaker spacing

- apps/player/src/components/play-button/PlayButton.vue
- package-lock.json
- packages/components/src/components/icons/__snapshots__/icon.test.js.snap
- packages/components/src/components/icons/states/Loading.vue
- packages/components/src/components/play-button/PlayButton.vue
- packages/components/src/components/play-button/__snapshots__/play-button.test.js.snap
- packages/components/src/components/play-button/states/Loading.vue
- packages/components/src/components/play-button/states/Pause.vue
- packages/components/src/components/play-button/states/Play.vue
- packages/components/src/components/play-button/states/Restart.vue
- packages/components/src/components/play-button/story.js
- packages/components/src/theme/tokens/play-button.scss
> chore(player): add size parameter to play button

- apps/player/src/components/episode-title/EpisodeTitle.vue
> fix(player): fix episode title line truncation

- packages/player/state/playlist/reducer.js
> feat(player): use provided active property to mark entry active

- apps/player/lang/fr.json
- apps/player/lang/index.js
- apps/subscribe-button/lang/fr.json
- apps/subscribe-button/lang/index.js
I translated every Localization file I found here because we love Podlove too ❤ .
Please tell me if there is more to translate in this repo.
> 🇫🇷 French Localization

- docs/web-player/installation.md
so turns out the url itself was wrong as well (sorry for creating 3 prs instead of 1 with 3 commits :upside_down_face: )
> fix config url

- README.md
Fixed some small typos in the readme.
> chore(documentation): fix library typos

- apps/subscribe-button/src/components/finish-card/FinishCard.vue
> fix(subscribe-button): remove custom color on end card link

- apps/player/cypress/integration/tab-chapters.spec.js
- packages/components/src/components/chapter-progress/ChapterProgress.vue
- packages/components/src/components/chapter-progress/__snapshots__/chapter-progress.test.js.snap
see github issue podlove#741 for details
> fix: Chapters: Only mark active chapters if playtime is greater 0

- apps/subscribe-button/src/List.vue
> fix(subscribe-button): use runtime locale

- packages/components/src/components/channel/states/Mail.vue
- packages/utils/package.json
- packages/utils/url.js
> fix(components): fix issue with mail share in firefox

- packages/button/react/src/index.jsx
@alexander-heimbuch We forgot to hand over the format data attribute. I added it.
> feat: add format data attribute to react subscribe button
